# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GitCode/SketchSystem_1080p/sketchSystem1080.cache/wt [current_project]
set_property parent.project_path D:/GitCode/SketchSystem_1080p/sketchSystem1080.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths d:/GitCode/Sketch_IP_1080p [current_project]
set_property ip_output_repo d:/GitCode/SketchSystem_1080p/sketchSystem1080.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/hdl/system_wrapper.v
add_files D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_dma_0_0/system_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axis_dwidth_converter_0_0/system_axis_dwidth_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_12/bd_44e3_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_18/bd_44e3_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_25/bd_44e3_s02a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_38/bd_44e3_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_39/bd_44e3_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_40/bd_44e3_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_30/bd_44e3_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_19/bd_44e3_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_21/bd_44e3_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_13/bd_44e3_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_14/bd_44e3_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_4/bd_44e3_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_5/bd_44e3_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_6/bd_44e3_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_7/bd_44e3_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_8/bd_44e3_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_1/bd_44e3_psr0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_2/bd_44e3_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_3/bd_44e3_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_v_tc_0_0/system_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_0_148M_0/system_rst_clk_wiz_0_148M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_0_148M_0/system_rst_clk_wiz_0_148M_0.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_rst_clk_wiz_0_148M_0/system_rst_clk_wiz_0_148M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/sources_1/ip/outputBuffer/outputBuffer.xdc]
set_property used_in_synthesis false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_auto_cc_0/system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/system_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/constrs_1/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_wrapper -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
