# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/system_SketchIP_1080p_0_0.xci
# IP: The module: 'system_SketchIP_1080p_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/sources_1/ip/outputBuffer/outputBuffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/sources_1/ip/outputBuffer/outputBuffer.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/system_SketchIP_1080p_0_0.xci
# IP: The module: 'system_SketchIP_1080p_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/sources_1/ip/outputBuffer/outputBuffer.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] -quiet

# XDC: d:/GitCode/SketchSystem_1080p/sketchSystem1080.srcs/sources_1/bd/system/ip/system_SketchIP_1080p_0_0/sources_1/ip/outputBuffer/outputBuffer.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==outputBuffer || ORIG_REF_NAME==outputBuffer} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
